# CancelSounds by: Beelzebu
# Cancel any server side sound
# You can find the sounds in https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html

Sounds:
- ENTITY_PLAYER_ATTACK_SWEEP
- ENTITY_PLAYER_ATTACK_NODAMAGE
- ENTITY_PLAYER_ATTACK_STRONG
- ENTITY_PLAYER_ATTACK_KNOCKBACK
- ENTITY_PLAYER_ATTACK_CRIT
- ENTITY_PLAYER_ATTACK_WEAK

# Replace sounds, format: 'sound:replacement'
Replace:
- 'HURT_FLESH:ARROW_HIT'